// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ginTemplate/app/connections"
	"ginTemplate/internal/controller"
	"ginTemplate/internal/repository"
	"ginTemplate/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *Initialization {
	db := connections.ConnectToDB()
	testRepositoryImpl := repository.TestRepositoryInit(db)
	testServiceImpl := service.TestServiceInit(testRepositoryImpl)
	testControllerImpl := controller.TestControllerInit(testServiceImpl)
	initialization := NewInitialization(testControllerImpl)
	return initialization
}

// wire.go:

var connectionsSet = wire.NewSet(connections.ConnectToDB, connections.ConnectToNatsBroker, connections.ConnectToRedis)

var testSet = wire.NewSet(repository.TestRepositoryInit, wire.Bind(new(repository.TestRepository), new(*repository.TestRepositoryImpl)), service.TestServiceInit, wire.Bind(new(service.TestService), new(*service.TestServiceImpl)), controller.TestControllerInit, wire.Bind(new(controller.TestController), new(*controller.TestControllerImpl)))
